package fr.acinq.eclair.wallet.models;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig paymentDaoConfig;

    private final PaymentDao paymentDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        paymentDaoConfig = daoConfigMap.get(PaymentDao.class).clone();
        paymentDaoConfig.initIdentityScope(type);

        paymentDao = new PaymentDao(paymentDaoConfig, this);

        registerDao(Payment.class, paymentDao);
    }
    
    public void clear() {
        paymentDaoConfig.clearIdentityScope();
    }

    public PaymentDao getPaymentDao() {
        return paymentDao;
    }

}
